name: task 2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v5
        id: build-image
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true               
          tags: |
            docker.io/${{ secrets.DOCKER_USERNAME }}/zadanie2:latest
            ghcr.io/${{ github.repository_owner }}/zadanie2:latest
          cache-from: type=registry,ref=docker.io/${{ secrets.DOCKER_USERNAME }}/cache:latest
          cache-to: type=registry,ref=docker.io/${{ secrets.DOCKER_USERNAME }}/cache:latest,mode=max

      - name: Scan image for vulnerabilities
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: docker.io/${{ secrets.DOCKER_USERNAME }}/zadanie2:latest
          exit-code: 0
          severity: CRITICAL,HIGH

